version: "3.2"

services:
#MariaDB Container
  mariadb:
    image: mariadb:10.7
    container_name: mariadb
    hostname: mariadb
    volumes:
      - ./storage/mysql:/var/lib/mysql
    env_file:
      - ./mariadb.env
    restart: always

#GLPI Container
  glpi:
    build: .
    container_name : glpi
    hostname: glpi
    ports:
      - "80:80"
    environment:
      - TIMEZONE=Europe/Brussels
    restart: always
